# Generated by Django 6.0.1 on 2026-05-20 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hardware_integration', '0001_initial'),
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gavetadinero',
            name='usuario_ultima_apertura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='impresora',
            index=models.Index(fields=['tipo_impresora', 'estado'], name='hw_impresor_tipo_im_5cf9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='impresora',
            index=models.Index(fields=['es_principal_tickets'], name='hw_impresor_es_prin_f04392_idx'),
        ),
        migrations.AddIndex(
            model_name='impresora',
            index=models.Index(fields=['es_principal_facturas'], name='hw_impresor_es_prin_362b86_idx'),
        ),
        migrations.AddIndex(
            model_name='impresora',
            index=models.Index(fields=['es_principal_etiquetas'], name='hw_impresor_es_prin_456651_idx'),
        ),
        migrations.AddField(
            model_name='gavetadinero',
            name='impresora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gavetas', to='hardware_integration.impresora'),
        ),
        migrations.AddField(
            model_name='plantillaimpresion',
            name='impresora',
            field=models.ForeignKey(blank=True, help_text='Impresora específica para esta plantilla', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas', to='hardware_integration.impresora'),
        ),
        migrations.AddField(
            model_name='registroimpresion',
            name='impresora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impresiones', to='hardware_integration.impresora'),
        ),
        migrations.AddField(
            model_name='registroimpresion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='registroimpresion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroimpresion',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='trabajoimpresion',
            name='impresora',
            field=models.ForeignKey(blank=True, help_text='Impresora específica (null = usar predeterminada)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_pendientes', to='hardware_integration.impresora'),
        ),
        migrations.AddField(
            model_name='trabajoimpresion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_impresion', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='trabajoimpresion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_impresion_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trabajoimpresion',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_impresion', to='ventas.venta'),
        ),
        migrations.AlterUniqueTogether(
            name='plantillaimpresion',
            unique_together={('tipo_documento', 'es_predeterminada')},
        ),
        migrations.AddIndex(
            model_name='registroimpresion',
            index=models.Index(fields=['-fecha_impresion'], name='hw_registro_fecha_i_6a0699_idx'),
        ),
        migrations.AddIndex(
            model_name='registroimpresion',
            index=models.Index(fields=['impresora', '-fecha_impresion'], name='hw_registro_impreso_bcd07b_idx'),
        ),
        migrations.AddIndex(
            model_name='registroimpresion',
            index=models.Index(fields=['tipo_documento', 'estado'], name='hw_registro_tipo_do_b3e8f8_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajoimpresion',
            index=models.Index(fields=['estado', 'prioridad', 'fecha_creacion'], name='hw_trabajo__estado_f094c7_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajoimpresion',
            index=models.Index(fields=['impresora', 'estado'], name='hw_trabajo__impreso_97a53f_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajoimpresion',
            index=models.Index(fields=['venta'], name='hw_trabajo__venta_i_66936f_idx'),
        ),
    ]
