# Generated by Django 6.0.1 on 2026-05-20 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='canjeopuntos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canjeopuntos',
            name='venta_utilizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canjes_utilizados', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='canjeopuntos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='detallepedidoonline',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='historialcliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='historialcliente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialcliente',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='moto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='moto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.marca'),
        ),
        migrations.AddField(
            model_name='movimientopuntos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_puntos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='movimientopuntos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientopuntos',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente registrado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidosonline', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_online', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='historialcliente',
            name='pedido_online',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.pedidoonline'),
        ),
        migrations.AddField(
            model_name='detallepedidoonline',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='clientes.pedidoonline'),
        ),
    ]
