# Generated by Django 6.0.1 on 2026-05-20 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_codigo', models.CharField(max_length=50, verbose_name='CÃ³digo del producto')),
                ('producto_nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('cantidad_enviada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad enviada')),
                ('cantidad_recibida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad recibida')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Detalle de Transferencia',
                'verbose_name_plural': 'Detalles de Transferencia',
                'ordering': ['producto_nombre'],
            },
        ),
        migrations.CreateModel(
            name='InventarioAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ajuste', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motivo', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('compra_ref', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de Compra')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(max_length=50, unique=True, verbose_name='CÃ³digo Ãšnico')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='DescripciÃ³n')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('incluye_iva', models.BooleanField(default=True, verbose_name='Incluye IVA')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock MÃ\xadnimo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('es_editable', models.BooleanField(default=False, verbose_name='Es Editable (Nombre/Precio)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=100, null=True, verbose_name='UbicaciÃ³n en AlmacÃ©n')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Principal')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen 2')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen 3')),
                ('codigo_barras', models.ImageField(blank=True, editable=False, null=True, upload_to='barcodes/')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de envÃ\xado'), ('EN_TRANSITO', 'En trÃ¡nsito'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envÃ\xado')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de recepciÃ³n')),
                ('numero_guia', models.CharField(editable=False, max_length=50, unique=True, verbose_name='NÃºmero de guÃ\xada')),
                ('observaciones_envio', models.TextField(blank=True, null=True, verbose_name='Observaciones del envÃ\xado')),
                ('observaciones_recepcion', models.TextField(blank=True, null=True, verbose_name='Observaciones de la recepciÃ³n')),
            ],
            options={
                'verbose_name': 'Transferencia de Inventario',
                'verbose_name_plural': 'Transferencias de Inventario',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porcentaje_ganancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='inventario.categoriaproducto')),
            ],
            options={
                'verbose_name': 'CategorÃ\xada de Producto',
                'verbose_name_plural': 'CategorÃ\xadas de Productos',
            },
        ),
    ]
