# Generated by Django 6.0.1 on 2026-05-20 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioajuste',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.marca'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='inventarioajuste',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='transferenciainventario',
            name='sucursal_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recibidas', to='core.sucursal', verbose_name='Sucursal Destino'),
        ),
        migrations.AddField(
            model_name='transferenciainventario',
            name='sucursal_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='core.sucursal', verbose_name='Sucursal Origen'),
        ),
        migrations.AddField(
            model_name='transferenciainventario',
            name='usuario_envia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que envÃ\xada'),
        ),
        migrations.AddField(
            model_name='transferenciainventario',
            name='usuario_recibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que recibe'),
        ),
        migrations.AddField(
            model_name='detalletransferencia',
            name='transferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.transferenciainventario', verbose_name='Transferencia'),
        ),
        migrations.AddIndex(
            model_name='transferenciainventario',
            index=models.Index(fields=['sucursal_origen', 'estado'], name='inventario__sucursa_28dcd6_idx'),
        ),
        migrations.AddIndex(
            model_name='transferenciainventario',
            index=models.Index(fields=['sucursal_destino', 'estado'], name='inventario__sucursa_737469_idx'),
        ),
        migrations.AddIndex(
            model_name='transferenciainventario',
            index=models.Index(fields=['numero_guia'], name='inventario__numero__859968_idx'),
        ),
    ]
