# Generated by Django 6.0.1 on 2026-05-20 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electronic_invoicing', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteelectronico',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante_electronico', to='ventas.venta'),
        ),
        migrations.AlterUniqueTogether(
            name='puntoemision',
            unique_together={('establecimiento', 'punto_emision')},
        ),
        migrations.AddField(
            model_name='comprobanteelectronico',
            name='punto_emision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='electronic_invoicing.puntoemision'),
        ),
    ]
