# Generated by Django 5.2.1 on 2026-05-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_integration', '0003_remove_trabajoimpresion_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresora',
            name='tipo_impresora',
            field=models.CharField(choices=[('TERMICA_80MM', 'Térmica 80mm (Facturas/Tickets)'), ('TERMICA_58MM', 'Térmica 58mm (Tickets/Recibos)'), ('ETIQUETAS', 'Impresora de Etiquetas'), ('LASER_PDF', 'Láser / PDF (A4/Carta)'), ('OTRA', 'Otra')], max_length=20),
        ),
    ]
