# Generated by Django 6.0.1 on 2026-05-20 00:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gastos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CierreDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('REVISADO', 'Revisado')], default='ABIERTO', max_length=10)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ventas_productos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ventas_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ventas_online', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ordenes_taller', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_iva_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad_ventas', models.IntegerField(default=0)),
                ('efectivo_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tarjeta_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transferencia_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credito_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('efectivo_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diferencia_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('observaciones_diferencias', models.TextField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cierre Diario',
                'verbose_name_plural': 'Cierres Diarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DesgloseBilletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BILLETE', 'Billete'), ('MONEDA', 'Moneda')], max_length=10)),
                ('denominacion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Desglose de Billetes',
                'verbose_name_plural': 'Desglose de Billetes',
                'ordering': ['-denominacion'],
            },
        ),
        migrations.CreateModel(
            name='GastoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('archivo_factura', models.FileField(blank=True, null=True, upload_to='facturas_gastos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('es_ingreso', models.BooleanField()),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('CREDITO', 'Crédito')], default='EFECTIVO', max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('archivo_soporte', models.FileField(blank=True, null=True, upload_to='soportes_caja/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='ResumenMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_ventas_productos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_ventas_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_ventas_online', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_ordenes_taller', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cantidad_ventas', models.IntegerField(default=0)),
                ('cantidad_gastos', models.IntegerField(default=0)),
                ('dias_operacion', models.IntegerField(default=0)),
                ('promedio_venta_dia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('promedio_gasto_dia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('utilidad_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('margen_utilidad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_generacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resumen Mensual',
                'verbose_name_plural': 'Resúmenes Mensuales',
                'ordering': ['-año', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento',
                'verbose_name_plural': 'Tipos de Movimientos',
                'ordering': ['tipo', 'nombre'],
            },
        ),
    ]
