# Generated by Django 6.0.1 on 2026-05-20 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrediario',
            name='usuario_cierre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cierrediario',
            name='usuario_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='desglosebilletes',
            name='cierre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desglose_billetes', to='reportes.cierrediario'),
        ),
        migrations.AddField(
            model_name='gastodiario',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gastodiario',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reportes.categoriagasto'),
        ),
        migrations.AddField(
            model_name='gastodiario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.venta'),
        ),
        migrations.AlterUniqueTogether(
            name='resumenmensual',
            unique_together={('año', 'mes')},
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='tipo_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportes.tipomovimiento'),
        ),
        migrations.AddIndex(
            model_name='cierrediario',
            index=models.Index(fields=['fecha'], name='reportes_ci_fecha_a96d60_idx'),
        ),
        migrations.AddIndex(
            model_name='cierrediario',
            index=models.Index(fields=['estado'], name='reportes_ci_estado_244b21_idx'),
        ),
        migrations.AddIndex(
            model_name='gastodiario',
            index=models.Index(fields=['fecha'], name='reportes_ga_fecha_d19219_idx'),
        ),
        migrations.AddIndex(
            model_name='gastodiario',
            index=models.Index(fields=['categoria'], name='reportes_ga_categor_ae8fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='gastodiario',
            index=models.Index(fields=['aprobado'], name='reportes_ga_aprobad_a192a3_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['fecha'], name='reportes_mo_fecha_fbdd7a_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['es_ingreso'], name='reportes_mo_es_ingr_912290_idx'),
        ),
    ]
