# Generated by Django 6.0.1 on 2026-05-20 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('total_productos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_reembolsos', models.DecimalField(decimal_places=2, default=0, help_text='Dinero devuelto a clientes', max_digits=10)),
                ('total_ingresos_extra', models.DecimalField(decimal_places=2, default=0, help_text='Dinero extra cobrado por cambios a mayor valor', max_digits=10)),
                ('ventas_netas', models.DecimalField(decimal_places=2, default=0, help_text='Ventas + Ingresos Extras - Reembolsos', max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('total_devuelto', models.DecimalField(decimal_places=2, default=0, help_text='Total de productos devueltos por el cliente', max_digits=10)),
                ('total_nuevo', models.DecimalField(decimal_places=2, default=0, help_text='Total de productos nuevos entregados al cliente', max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, help_text='Si es < 0, se reembolsa dinero. Si es > 0, el cliente paga más.', max_digits=10)),
                ('estado', models.CharField(choices=[('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='COMPLETADA', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEVUELTO', 'Producto Devuelto (Entra a Stock)'), ('NUEVO', 'Producto Nuevo (Sale de Stock)')], max_length=10)),
                ('nombre_personalizado', models.CharField(blank=True, help_text='Nombre para items manuales o genéricos', max_length=200, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.devolucion')),
            ],
            options={
                'verbose_name': 'Detalle de Devolución',
                'verbose_name_plural': 'Detalles de Devolución',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='COMPLETADA', max_length=20)),
                ('tipo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE', 'Cheque'), ('CREDITO', 'Crédito')], max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('datos_pago', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='devolucion',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.venta'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento aplicado', max_digits=5)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('nombre_personalizado', models.CharField(blank=True, help_text='Nombre para items manuales, servicios o genéricos', max_length=200, null=True)),
                ('es_servicio', models.BooleanField(default=False, help_text='Indica si este detalle es un servicio (sin IVA)')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
